import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawn} from 'node:child_process';
import { LsgStore } from '../src/core/db.mjs';import { LsgService } from '../src/core/service.mjs';import { McpProtocol, MODERN_PROTOCOL } from '../src/mcp/protocol.mjs';import { createHttpServer } from '../src/http/server.mjs';

async function httpRuntime(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lsg-http-'));const store=new LsgStore(path.join(dir,'db.sqlite'));const service=new LsgService(store,{workspaceRoot:dir});const protocol=new McpProtocol(service);const config={host:'127.0.0.1',port:0,dbPath:path.join(dir,'db.sqlite'),workspaceRoot:dir,apiToken:'test-token',allowInsecure:false,allowedOrigins:[],allowedHosts:[],maxBodyBytes:2*1024*1024,rateLimitPerMinute:1000,logLevel:'error',upstreamBaseUrl:'',upstreamApiKey:'',modelMap:{'lsg-auto':'fake'}};const app=createHttpServer({service,protocol,config,log:()=>{}});const addr=await app.listen();const base=`http://127.0.0.1:${addr.port}`;return{dir,store,service,app,base,close:async()=>{await app.close();store.close();fs.rmSync(dir,{recursive:true,force:true});}}}
async function jfetch(url,opts={}){const r=await fetch(url,{...opts,headers:{authorization:'Bearer test-token','content-type':'application/json',...(opts.headers||{})}});const j=await r.json().catch(()=>null);return{r,j};}
const modernMeta={"io.modelcontextprotocol/protocolVersion":MODERN_PROTOCOL,"io.modelcontextprotocol/clientCapabilities":{tools:{},resources:{},prompts:{}}};
async function mcp(base,id,method,params={}){const principal=method==='tools/call'?params.name:method==='resources/read'?params.uri:method==='prompts/get'?params.name:'';const body={jsonrpc:'2.0',id,method,params:{...params,_meta:{...(params._meta||{}),...modernMeta}}};const h={authorization:'Bearer test-token','content-type':'application/json','mcp-protocol-version':MODERN_PROTOCOL,'mcp-method':method};if(principal)h['mcp-name']=principal;const r=await fetch(base+'/mcp',{method:'POST',headers:h,body:JSON.stringify(body)});return{r,j:await r.json()};}

test('HTTP E2E: MCP bootstrap -> graph -> edge case -> implementation -> verification -> audit -> UI',async()=>{const x=await httpRuntime();try{
  const ui=await (await fetch(x.base+'/')).text();assert.match(ui,/Semantic backlog/);const uiJs=await (await fetch(x.base+'/app.js')).text();assert.match(uiJs,/semantic\/edge-cases/);
  let q=await mcp(x.base,1,'server/discover');assert.equal(q.r.status,200);assert.ok(q.j.result.supportedVersions.includes(MODERN_PROTOCOL));
  q=await mcp(x.base,2,'tools/call',{name:'solution.create_project',arguments:{project_id:'web1',title:'Payments site'}});assert.equal(q.j.result.structuredContent.id,'web1');
  const project=(await jfetch(x.base+'/api/projects/web1')).j;
  const plan='# Payments portal\n\n- Website frontend\n- Backend API\n- Database for customers\n- User login\n- Stripe-style payment processing\n- [x] Initial frontend shell\n';
  q=await mcp(x.base,3,'tools/call',{name:'solution.preview_markdown_plan',arguments:{project_id:'web1',markdown:plan,file_name:'plan.md',expected_graph_version:project.graph_version,starter_pack_mode:'auto',allow_model_edge_case_expansion:true}});assert.notEqual(q.j.result.isError,true);const preview=q.j.result.structuredContent;assert.ok(preview.analysis.candidates.length>10);
  q=await mcp(x.base,4,'tools/call',{name:'solution.commit_plan_import',arguments:{project_id:'web1',import_session_id:preview.id,expected_graph_version:preview.expected_graph_version}});assert.notEqual(q.j.result.isError,true);
  q=await mcp(x.base,5,'tools/call',{name:'solution.get_graph_view',arguments:{project_id:'web1'}});const graph=q.j.result.structuredContent;assert.ok(graph.nodes.length>10);assert.ok(graph.edges.length>0);
  const parent=graph.nodes.find(n=>n.type==='feature');assert.ok(parent);
  let gv=graph.project.graph_version;q=await mcp(x.base,6,'tools/call',{name:'solution.add_edge_case',arguments:{project_id:'web1',parent_feature_id:parent.id,title:'Unexpected downstream timeout after partial success',description:'Ensure retry is safe',expected_graph_version:gv,origin:'model_discovery'}});const ec=q.j.result.structuredContent;assert.equal(ec.implemented,false);
  gv=(await jfetch(x.base+'/api/projects/web1')).j.graph_version;q=await mcp(x.base,7,'tools/call',{name:'solution.set_implementation_state',arguments:{project_id:'web1',node_id:ec.id,implemented:true,expected_graph_version:gv,expected_node_version:ec.version,commit_sha:'c0ffee12',reason:'Implemented defensive retry'}});const impl=q.j.result.structuredContent;assert.equal(impl.implemented,true);
  gv=(await jfetch(x.base+'/api/projects/web1')).j.graph_version;q=await mcp(x.base,8,'tools/call',{name:'solution.set_verification_state',arguments:{project_id:'web1',node_id:ec.id,verification_state:'verified',expected_graph_version:gv,expected_node_version:impl.version,evidence:{kind:'e2e',summary:'Injected timeout and confirmed idempotent recovery'}}});assert.equal(q.j.result.structuredContent.verification_state,'verified');
  q=await mcp(x.base,9,'tools/call',{name:'solution.audit_implementation_status',arguments:{project_id:'web1'}});const audit=q.j.result.structuredContent;assert.ok(audit.verified.some(n=>n.id===ec.id));assert.ok(audit.not_implemented.length>0);
  let u=await jfetch(x.base+'/v1/user-history/entries',{method:'POST',body:JSON.stringify({user_id:'u1',text:'I prefer self-hosted services',kind:'preference',subject:'hosting'})});assert.equal(u.r.status,201);u=await jfetch(x.base+'/v1/user-history/context?user_id=u1&project_id=web1&budget_tokens=100');assert.ok(u.j.summary.includes('self-hosted'));
  const html=await fetch(x.base+'/').then(r=>r.text());assert.match(html,/Living Solution Graph/);const js=await fetch(x.base+'/app.js').then(r=>r.text());assert.match(js,/renderGraph/);
  const models=await jfetch(x.base+'/v1/models');assert.equal(models.r.status,200);assert.ok(models.j.data.some(m=>m.id==='lsg-auto'));
  const notConfigured=await jfetch(x.base+'/v1/responses',{method:'POST',body:JSON.stringify({model:'lsg-auto',input:'hello'})});assert.equal(notConfigured.r.status,503);
}finally{await x.close();}});

test('HTTP security: unauthenticated API/MCP rejected while health remains public',async()=>{const x=await httpRuntime();try{let r=await fetch(x.base+'/healthz');assert.equal(r.status,200);r=await fetch(x.base+'/api/projects');assert.equal(r.status,401);r=await fetch(x.base+'/mcp',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});assert.equal(r.status,401);}finally{await x.close();}});



test('HTTP modern envelope without required standard headers is rejected with header mismatch',async()=>{const x=await httpRuntime();try{const body={jsonrpc:'2.0',id:1,method:'tools/list',params:{_meta:modernMeta}};const r=await fetch(x.base+'/mcp',{method:'POST',headers:{authorization:'Bearer test-token','content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();assert.equal(r.status,400);assert.equal(j.error.code,-32020);}finally{await x.close();}});

test('stdio E2E: modern 2026 discover and tool listing carry complete resultType',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lsg-stdio-modern-'));const child=spawn(process.execPath,['src/cli.mjs','stdio'],{cwd:path.resolve('.'),env:{...process.env,LSG_DB_PATH:path.join(dir,'db.sqlite'),LSG_WORKSPACE_ROOT:dir},stdio:['pipe','pipe','pipe']});const lines=[];let buffer='';child.stdout.setEncoding('utf8');child.stdout.on('data',d=>{buffer+=d;let i;while((i=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,i);buffer=buffer.slice(i+1);if(line.trim())lines.push(JSON.parse(line));}});const waitFor=async id=>{for(let k=0;k<100;k++){const v=lines.find(v=>v.id===id);if(v)return v;await new Promise(r=>setTimeout(r,20));}throw new Error('Timeout waiting for stdio response');};const mm=(id,method,params={})=>({jsonrpc:'2.0',id,method,params:{...params,_meta:{...modernMeta}}});try{child.stdin.write(JSON.stringify(mm(1,'server/discover'))+'\n');let r=await waitFor(1);assert.equal(r.result.resultType,'complete');assert.deepEqual(r.result.supportedVersions,[MODERN_PROTOCOL]);child.stdin.write(JSON.stringify(mm(2,'tools/list'))+'\n');r=await waitFor(2);assert.equal(r.result.resultType,'complete');assert.ok(r.result.tools.length>20);}finally{child.stdin.end();await new Promise(resolve=>{child.once('exit',resolve);setTimeout(()=>{child.kill('SIGTERM');resolve();},500)});fs.rmSync(dir,{recursive:true,force:true});}});

test('stdio E2E: legacy initialize, tool call, and tools/list over newline-delimited JSON',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lsg-stdio-'));const child=spawn(process.execPath,['src/cli.mjs','stdio'],{cwd:path.resolve('.'),env:{...process.env,LSG_DB_PATH:path.join(dir,'db.sqlite'),LSG_WORKSPACE_ROOT:dir},stdio:['pipe','pipe','pipe']});const lines=[];let buffer='';child.stdout.setEncoding('utf8');child.stdout.on('data',d=>{buffer+=d;let i;while((i=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,i);buffer=buffer.slice(i+1);if(line.trim())lines.push(JSON.parse(line));}});const waitFor=async id=>{for(let k=0;k<100;k++){const x=lines.find(x=>x.id===id);if(x)return x;await new Promise(r=>setTimeout(r,20));}throw new Error(`Timeout waiting for ${id}; stderr unknown`);};try{
  child.stdin.write(JSON.stringify({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-11-25',capabilities:{},clientInfo:{name:'e2e',version:'1'}}})+'\n');let x=await waitFor(1);assert.equal(x.result.serverInfo.name,'living-solution-graph');
  child.stdin.write(JSON.stringify({jsonrpc:'2.0',method:'notifications/initialized',params:{}})+'\n');
  child.stdin.write(JSON.stringify({jsonrpc:'2.0',id:2,method:'tools/list',params:{}})+'\n');x=await waitFor(2);assert.ok(x.result.tools.some(t=>t.name==='solution.bootstrap_from_markdown_plan'));
  child.stdin.write(JSON.stringify({jsonrpc:'2.0',id:3,method:'tools/call',params:{name:'solution.create_project',arguments:{project_id:'stdio-p',title:'Stdio project'}}})+'\n');x=await waitFor(3);assert.equal(x.result.structuredContent.id,'stdio-p');
}finally{child.stdin.end();await new Promise(resolve=>{child.once('exit',resolve);setTimeout(()=>{child.kill('SIGTERM');resolve();},500)});fs.rmSync(dir,{recursive:true,force:true});}});
