import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { LsgStore } from '../src/core/db.mjs';
import { LsgService } from '../src/core/service.mjs';
import { McpProtocol } from '../src/mcp/protocol.mjs';

function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lsg-plans-')),store=new LsgStore(path.join(dir,'data','lsg.sqlite')),service=new LsgService(store,{workspaceRoot:dir});service.createProject({project_id:'p',title:'Game',metadata:{workspace_root:dir}});const feature=store.insertNode({project_id:'p',type:'feature',title:'Cockpit',description:'Pilot can enter',metadata:{layer:'semantic',semantic_key:'cockpit',display_id:'F1',priority:'P0',acceptance_criteria:['Pilot enters']}}),child=store.insertNode({project_id:'p',type:'feature',title:'Flight controls',parent_id:feature.id,metadata:{layer:'semantic',semantic_key:'flight',display_id:'F1.1',parent_semantic_key:'cockpit',priority:'P1'}}),edgeCase=store.insertNode({project_id:'p',type:'edge_case',title:'Pilot disconnect',parent_id:feature.id,metadata:{layer:'semantic',semantic_key:'disconnect',display_id:'F1.E1',trigger:'Disconnect',expected_behavior:'Control is released'}});store.insertEdge({project_id:'p',source_id:feature.id,target_id:edgeCase.id,type:'has_edge_case'});return {dir,store,service,feature,child,edgeCase,close(){store.close();fs.rmSync(dir,{recursive:true,force:true});}};}

test('missing-plan pages remain bounded and stable as earlier plans are written',()=>{const r=fixture();try{const first=r.service.getNextMissingPlans({project_id:'p',limit:2});assert.equal(first.items.length,2);assert.ok(first.next_cursor);assert.equal(first.items[0].display_id,'F1');r.service.setNodeImplementationPlan({project_id:'p',node_id:first.items[0].node_id,markdown:'# First'});const second=r.service.getNextMissingPlans({project_id:'p',limit:2,cursor:first.next_cursor});assert.equal(second.items.length,1);assert.equal(second.items[0].display_id,'F1.E1');assert.equal(second.next_cursor,null);assert.throws(()=>r.service.getNextMissingPlans({project_id:'p',cursor:'broken'}),/cursor/i);r.store.bumpGraphVersion('p');assert.throws(()=>r.service.getNextMissingPlans({project_id:'p',cursor:first.next_cursor}),/stale/i);}finally{r.close();}});

test('bulk plan staging is reviewable, confirmation-bound, versioned, and atomic',()=>{const r=fixture();try{let graph=r.store.getProject('p').graph_version;const plans=[r.feature,r.edgeCase].map(node=>({node_id:node.id,markdown:`# ${node.title}\n\nImplement and verify.`}));let batch=r.service.stagePlanBatch({project_id:'p',expected_graph_version:graph,plans});assert.equal(batch.status,'staged');assert.equal(batch.diff.length,2);assert.equal(r.service.getImplementationPlanCoverage({project_id:'p'}).with_plan,0);assert.throws(()=>r.service.applyPlanBatch({project_id:'p',batch_id:batch.id,expected_graph_version:graph,confirm_plan_count:1}),/Confirm application/);r.service.setNodeImplementationPlan({project_id:'p',node_id:r.edgeCase.id,markdown:'# Intervening edit'});assert.throws(()=>r.service.applyPlanBatch({project_id:'p',batch_id:batch.id,expected_graph_version:graph,confirm_plan_count:2}),/version conflict/i);assert.equal(r.store.getNodeDocument(r.feature.id),null,'failed batch partially wrote first plan');batch=r.service.stagePlanBatch({project_id:'p',expected_graph_version:graph,plans});const applied=r.service.applyPlanBatch({project_id:'p',batch_id:batch.id,expected_graph_version:graph,confirm_plan_count:2});assert.equal(applied.status,'applied');assert.equal(r.service.getImplementationPlanCoverage({project_id:'p'}).with_plan,2);assert.equal(r.store.getNodeDocument(r.edgeCase.id).file_name,'F1.E1-implementation-plan.md');assert.throws(()=>r.service.applyPlanBatch({project_id:'p',batch_id:batch.id,expected_graph_version:graph,confirm_plan_count:2}),/Only a staged/);}finally{r.close();}});

test('managed project snapshots restore graph, plans, history, memory and imports without overwriting',()=>{const r=fixture();try{const session=r.service.previewMarkdownPlan({project_id:'p',markdown:'# Product\n- Build a cockpit',expected_graph_version:r.store.getProject('p').graph_version});r.service.setNodeImplementationPlan({project_id:'p',node_id:r.feature.id,markdown:'# Plan\n\nStep one.'});r.service.workspace.memory({project_id:'p',node_id:r.feature.id,text:'Use authoritative controls'},'remember');const exported=r.service.exportProjectSnapshot({project_id:'p'});assert.ok(fs.existsSync(exported.file_path));assert.equal(exported.record_counts.import_sessions,1);assert.throws(()=>r.service.restoreProjectSnapshot({file_path:exported.file_path,expected_sha256:exported.sha256,confirm_title:'Game'}),/already exists/);r.service.deleteProject({project_id:'p',confirm_title:'Game'});assert.throws(()=>r.service.restoreProjectSnapshot({file_path:exported.file_path,expected_sha256:'0'.repeat(64),confirm_title:'Game'}),/checksum/);assert.throws(()=>r.service.restoreProjectSnapshot({file_path:exported.file_path,expected_sha256:exported.sha256,confirm_title:'Wrong'}),/Confirm restore/);const restored=r.service.restoreProjectSnapshot({file_path:exported.file_path,expected_sha256:exported.sha256,confirm_title:'Game'});assert.equal(restored.restored,true);assert.equal(r.store.getProject('p').title,'Game');assert.equal(r.store.getNode(r.feature.id).title,'Cockpit');assert.match(r.store.getNodeDocument(r.feature.id).markdown,/Step one/);assert.equal(r.store.listImportSessions('p')[0].id,session.id);assert.ok(r.service.workspace.memory({project_id:'p'},'search').entries.length);assert.ok(r.store.db.prepare('SELECT count(*) AS n FROM node_revisions WHERE project_id=?').get('p').n>0);assert.equal(r.store.db.prepare('PRAGMA foreign_key_check').all().length,0);}finally{r.close();}});

test('new plan and snapshot tools are discoverable over MCP',()=>{const r=fixture();try{const names=new Set(new McpProtocol(r.service).tools.keys());for(const name of ['solution.get_next_missing_plans','solution.stage_plan_batch','solution.get_plan_batch','solution.apply_plan_batch','solution.export_project_snapshot','solution.restore_project_snapshot'])assert.ok(names.has(name),name);}finally{r.close();}});
