import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {LsgStore} from '../src/core/db.mjs';
import {LsgService} from '../src/core/service.mjs';
import {importanceScale} from '../src/core/workspace.mjs';
import {McpProtocol} from '../src/mcp/protocol.mjs';
import {placeCards,placeRadialCards,ringRadius,routeConnection,intersects} from '../public/canvas-layout.js';

function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lsg-workspace-'));const store=new LsgStore(path.join(dir,'data','db.sqlite'));const service=new LsgService(store,{workspaceRoot:dir});service.createProject({project_id:'p',title:'Project',metadata:{workspace_root:dir}});const add=(key,type='feature',parent=null,extra={})=>store.insertNode({project_id:'p',type,title:key,parent_id:parent?.id,metadata:{layer:'semantic',semantic_key:key,display_id:key,priority:'P0',parent_semantic_key:parent?.metadata.semantic_key},...extra});const f=add('F1'),child=add('F1.1','feature',f),ec=add('F1.E1','edge_case',f),acceptance=add('test','test',child);store.insertEdge({project_id:'p',source_id:f.id,target_id:ec.id,type:'has_edge_case'});store.insertEdge({project_id:'p',source_id:child.id,target_id:ec.id,type:'has_edge_case'});return {dir,store,service,f,child,ec,acceptance,add,close(){store.close();fs.rmSync(dir,{recursive:true,force:true});}};}
const done=(r,n)=>r.store.updateNode(n.id,{implemented:true,implementation_state:'implemented',verification_state:'verified'});

test('source changes invalidate linked semantic verification without changing feature identity',()=>{const r=fixture();try{const source=r.add('source','requirement',null,{metadata:{layer:'source'}});r.store.updateNode(r.f.id,{metadata:{source_node_ids:[source.id]}});done(r,r.f);const before=r.store.getNode(r.f.id);r.store.updateNode(source.id,{description:'Updated requirement'});const after=r.store.getNode(r.f.id);assert.equal(after.verification_state,'stale');assert.equal(after.metadata.display_id,before.metadata.display_id);assert.equal(after.version,before.version+1);}finally{r.close();}});

test('successful task review verifies only the reviewed node, not unfinished descendants',()=>{const r=fixture();try{let work=r.service.workspace.work({project_id:'p',reference:'F1',owner:'agent'},'claim');r.store.updateNode(r.f.id,{implemented:true,implementation_state:'implemented'});work=r.service.workspace.work({project_id:'p',work_id:work.id,owner:'agent',expected_version:work.version,action:'submit',result:{summary:'Foundation implemented'}},'update');const reviewed=r.service.workspace.work({project_id:'p',work_id:work.id,expected_version:work.version,reviewer:'agent',approved:true,evidence:{kind:'automated_test',summary:'Foundation unit tests pass'}},'review');assert.equal(reviewed.status,'reviewed');assert.equal(r.store.getNode(r.f.id).verification_state,'verified');assert.notEqual(r.service.workspace.progress({project_id:'p',reference:'F1'}).items.find(n=>n.id===r.f.id).category,'fully_complete');}finally{r.close();}});

test('counts deduplicate shared cases and require descendants plus acceptance verification',()=>{const r=fixture();try{const a={project_id:'p'};let p=r.service.workspace.progress(a);assert.equal(p.combined_total,3);assert.equal(p.features_total,2);assert.equal(p.subfeatures,1);assert.equal(p.edge_cases_total,1);assert.equal(p.items.find(n=>n.id===r.f.id).recursive_edge_cases,1);done(r,r.f);assert.equal(r.service.workspace.progress(a).items.find(n=>n.id===r.f.id).category,'partially_implemented');for(const n of [r.child,r.ec])done(r,n);assert.equal(r.service.workspace.progress(a).items.find(n=>n.id===r.f.id).category,'partially_implemented');done(r,r.acceptance);assert.equal(r.service.workspace.progress(a).counts.fully_complete,3);r.store.updateNode(r.ec.id,{description:'Changed requirement'});assert.equal(r.service.workspace.progress(a).counts.stale,3);assert.ok(r.service.getFrontier(a).frontier.some(n=>n.id===r.f.id));const standalone=r.add('F2');done(r,standalone);assert.equal(r.service.workspace.progress({project_id:'p',reference:'F2'}).items[0].category,'fully_complete');r.store.updateNode(r.child.id,{status:'excluded'});assert.ok(r.service.workspace.progress(a).excluded.some(n=>n.id===r.child.id));}finally{r.close();}});

test('importance configuration maps referenced levels and preserves overrides',()=>{const r=fixture();try{const levels=[{id:'critical',label:'Critical',description:'Blocks delivery'}];assert.throws(()=>r.service.workspace.setScale({levels,expected_version:0}),/replacement/);r.service.workspace.setScale({levels,expected_version:0,replacements:{P0:'critical'}});assert.equal(importanceScale(r.store).version,1);assert.equal(r.store.getNode(r.f.id).metadata.priority,'critical');const node=r.store.getNode(r.f.id);r.service.workspace.setImportance({project_id:'p',reference:'F1',priority:'critical',rationale:'Required foundation',expected_node_version:node.version});assert.equal(r.store.getNode(r.f.id).metadata.importance_override,true);assert.throws(()=>r.service.workspace.setScale({levels,expected_version:0}),/changed/);}finally{r.close();}});

test('claim contention, renewal, submission, stale reviews, and expiry',()=>{const r=fixture();try{const a={project_id:'p',owner:'agent'};let work=r.service.workspace.work({...a,node_id:r.f.id},'claim');assert.throws(()=>r.service.workspace.work(a,'claim'),/active work/);work=r.service.workspace.work({...a,work_id:work.id,expected_version:work.version,action:'renew'},'update');r.store.updateNode(r.f.id,{implemented:true,implementation_state:'implemented'});work=r.service.workspace.work({...a,work_id:work.id,expected_version:work.version,action:'submit',result:{summary:'Implemented foundation'}},'update');assert.notEqual(r.store.getNode(r.f.id).verification_state,'verified');assert.throws(()=>r.service.workspace.work({project_id:'p',work_id:work.id,expected_version:work.version,approved:true,reviewer:'agent'},'review'),/evidence/);r.store.updateNode(r.f.id,{description:'Different requirement'});assert.throws(()=>r.service.workspace.work({project_id:'p',work_id:work.id,expected_version:work.version,approved:true,reviewer:'agent',evidence:{kind:'automated_test',summary:'Tests pass'}},'review'),/changed after submission/);r.service.workspace.put('work',work.id,'p',{...work,expires_at:new Date(0).toISOString()});assert.ok(r.service.workspace.work(a,'claim').id!==work.id);}finally{r.close();}});

test('project memory is isolated, bounded, correctable and forgotten without personal contamination',()=>{const r=fixture();try{r.service.createProject({project_id:'q',title:'Other'});const m=r.service.workspace.memory({project_id:'p',node_id:r.f.id,text:'The Frame requires authoritative input'},'remember');assert.equal(r.service.workspace.memory({project_id:'q'},'search').entries.length,0);assert.equal(r.service.workspace.memory({project_id:'p',budget_tokens:1},'context').entries.length,0);assert.throws(()=>r.service.workspace.memory({project_id:'q',memory_id:m.id,expected_version:1,text:'Bad'},'correct'),/not found/);const next=r.service.workspace.memory({project_id:'p',memory_id:m.id,expected_version:1,text:'Updated authoritative contract'},'correct');assert.equal(next.supersedes_id,m.id);r.service.workspace.memory({project_id:'p',memory_id:next.id,expected_version:1},'forget');assert.equal(r.service.workspace.memory({project_id:'p'},'search').entries.length,0);assert.equal(r.store.listMemories('p').length,0);}finally{r.close();}});

test('revision history preserves definitions and Markdown plans across database reopen',()=>{const r=fixture();try{r.store.updateNode(r.f.id,{title:'New name'});r.service.setNodeImplementationPlan({project_id:'p',node_id:r.f.id,markdown:'# First'});r.service.setNodeImplementationPlan({project_id:'p',node_id:r.f.id,markdown:'# Second',expected_document_version:1});const history=r.service.workspace.history({project_id:'p',reference:'F1'});assert.equal(history.revisions.length,2);assert.equal(history.records.filter(r=>r.kind==='plan').length,2);const other=new LsgStore(r.store.dbPath);assert.equal(other.db.prepare("SELECT value FROM meta WHERE key='schema_version'").get().value,'9');assert.equal(other.getNode(r.f.id).id,r.f.id);other.close();}finally{r.close();}});

test('activity is opt-in, ephemeral, debounced and excludes secrets, ignored paths and symlinks',async()=>{const r=fixture();try{const git=(...args)=>execFileSync('git',['-C',r.dir,...args],{stdio:'ignore',windowsHide:true});git('init');fs.mkdirSync(path.join(r.dir,'src'));fs.writeFileSync(path.join(r.dir,'src','a.txt'),'private source content');fs.writeFileSync(path.join(r.dir,'.gitignore'),'src/ignored.txt\n');fs.writeFileSync(path.join(r.dir,'src','ignored.txt'),'secret');assert.equal(r.service.activity.status({project_id:'p'}).enabled,false);r.service.activity.links({project_id:'p',reference:'F1',paths:['src']});for(const name of ['.env','src/ignored.txt','../outside','data/db.sqlite'])assert.throws(()=>r.service.activity.safe('p',name,{missing:true}),/excluded|escapes/);const outside=fs.mkdtempSync(path.join(os.tmpdir(),'lsg-outside-'));try{fs.symlinkSync(outside,path.join(r.dir,'src','link'),'junction');assert.throws(()=>r.service.activity.safe('p','src/link/file',{missing:true}),/Linked|escapes/);}finally{fs.rmSync(path.join(r.dir,'src','link'),{force:true});fs.rmSync(outside,{recursive:true,force:true});}
    const before=r.store.listEvents({project_id:'p'}).length;const events=[];r.service.activity.bus.on('p',e=>events.push(e));r.service.activity.enable({project_id:'p',enabled:true});assert.equal(r.service.activity.status({project_id:'p'}).watched,1,JSON.stringify(r.service.activity.status({project_id:'p'})));await new Promise(resolve=>setTimeout(resolve,100));r.service.activity.read({project_id:'p',reference:'F1',path:'src/a.txt'});for(let i=0;i<5;i++)fs.writeFileSync(path.join(r.dir,'src','a.txt'),'private source content '+i);await new Promise(resolve=>setTimeout(resolve,800));assert.ok(events.some(e=>e.kind==='file_read'));assert.ok(events.some(e=>e.kind==='workspace_change'));assert.ok(events.length<6);assert.ok(!JSON.stringify(events).includes('private source content'));assert.equal(r.store.listEvents({project_id:'p'}).length,before);r.service.activity.enable({project_id:'p',enabled:false});assert.equal(r.service.activity.status({project_id:'p'}).buffer_size,0);assert.equal(r.service.activity.sessions.size,0);
  }finally{r.close();}});

test('Git associations include stable URLs, tags and stats without storing patches',()=>{const r=fixture();try{const git=(...args)=>execFileSync('git',['-C',r.dir,...args],{encoding:'utf8',windowsHide:true});git('init');git('config','user.email','test@example.com');git('config','user.name','LSG test');git('remote','add','origin','git@github.com:example/game.git');fs.writeFileSync(path.join(r.dir,'game.txt'),'one\ntwo\n');git('add','game.txt');git('commit','-m','Implement frame');git('tag','v1');r.service.activity.links({project_id:'p',reference:'F1',paths:['game.txt']});const result=r.service.workspace.syncGit({project_id:'p'});assert.equal(result.commits.length,1);assert.match(result.commits[0].url,/^https:\/\/github.com\/example\/game\/commit\/[a-f0-9]+$/);assert.deepEqual(result.commits[0].tags,['v1']);assert.equal(result.commits[0].files[0].additions,2);assert.equal(result.commits[0].proof_of_implementation,false);}finally{r.close();}});

test('new tools are usable through MCP and count combined nodes',async()=>{const r=fixture();try{const protocol=new McpProtocol(r.service);const result=await protocol.handle({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'solution.get_counts',arguments:{project_id:'p'}}},{era:'legacy'});assert.equal(result.result.structuredContent.combined_total,3);for(const name of ['memory.get_project_context','solution.read_node_file','solution.update_semantic_edge_case','solution.delete_semantic_edge_case','solution.get_implementation_plan_coverage','solution.append_node_implementation_plan','solution.delete_node_implementation_plan','solution.delete_project'])assert.ok(protocol.tools.has(name),name);const coverage=await protocol.handle({jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'solution.get_implementation_plan_coverage',arguments:{project_id:'p',missing_only:true}}},{era:'legacy'});assert.equal(coverage.result.structuredContent.missing_plan,3);}finally{r.close();}});

test('semantic edge cases edit without renumbering, invalidate verification and leave tombstone history',()=>{const r=fixture();try{done(r,r.ec);const before=r.store.getNode(r.ec.id),a={project_id:'p',node_id:r.ec.id,expected_graph_version:r.store.getProject('p').graph_version,expected_node_version:before.version};assert.throws(()=>r.service.updateSemanticEdgeCase({...a,expected_node_version:0,title:'Wrong'}),/version conflict/i);const changed=r.service.updateSemanticEdgeCase({...a,title:'Conflicting recovery',trigger:'Two clients return together',expected_behavior:'Only one wins',validation_scenario:'Race two clients'});assert.equal(changed.metadata.display_id,'F1.E1');assert.equal(changed.metadata.semantic_key,before.metadata.semantic_key);assert.equal(changed.verification_state,'stale');assert.throws(()=>r.service.deleteSemanticEdgeCase({...a,expected_graph_version:r.store.getProject('p').graph_version,expected_node_version:changed.version,confirm_display_id:'F1.E2'}),/Confirm deletion/);const deleted=r.service.deleteSemanticEdgeCase({...a,expected_graph_version:r.store.getProject('p').graph_version,expected_node_version:changed.version,confirm_display_id:'F1.E1'});assert.equal(deleted.status,'deleted');assert.equal(r.service.getSemanticEdgeCases({project_id:'p'}).edge_cases.length,0);assert.equal(r.service.getImplementationPlanCoverage({project_id:'p'}).items.some(i=>i.node_id===r.ec.id),false);const next=r.service.addEdgeCase({project_id:'p',parent_feature_id:r.f.id,title:'Another case',expected_graph_version:r.store.getProject('p').graph_version});assert.equal(next.metadata.display_id,'F1.E2');assert.ok(r.store.db.prepare('SELECT count(*) AS n FROM node_revisions WHERE node_id=?').get(r.ec.id).n>=3);}finally{r.close();}});

test('plan coverage, append, replacement and confirmed removal preserve revision history',()=>{const r=fixture();try{const initial=r.service.getImplementationPlanCoverage({project_id:'p'});assert.equal(initial.total,3);assert.equal(initial.missing_plan,3);assert.equal(initial.items.find(i=>i.node_id===r.ec.id).file_name,'F1.E1-implementation-plan.md');const first=r.service.setNodeImplementationPlan({project_id:'p',node_id:r.ec.id,markdown:'# Recovery\n\nCheck first return.'});assert.equal(first.file_name,'F1.E1-implementation-plan.md');const second=r.service.appendNodeImplementationPlan({project_id:'p',node_id:r.ec.id,markdown:'## Race test\n\nStart two clients.',expected_document_version:1});assert.match(second.markdown,/# Recovery[\s\S]*## Race test/);assert.equal(r.service.getImplementationPlanCoverage({project_id:'p',missing_only:true}).missing_plan,2);assert.throws(()=>r.service.deleteNodeImplementationPlan({project_id:'p',node_id:r.ec.id,confirm_file_name:'wrong.md'}),/Confirm deletion/);r.service.deleteNodeImplementationPlan({project_id:'p',node_id:r.ec.id,confirm_file_name:second.file_name,expected_document_version:2});assert.equal(r.service.getImplementationPlanCoverage({project_id:'p'}).missing_plan,3);assert.equal(r.service.workspace.history({project_id:'p',reference:r.ec.id}).records.filter(x=>x.kind==='plan').length,2);}finally{r.close();}});

test('absolute plan path binds selected project and confirmed deletion removes only its records',()=>{const r=fixture();try{const plan=path.join(r.dir,'master-plan.md');fs.writeFileSync(plan,'# Game plan\n\n## Features\n\n- Build a cockpit.');assert.throws(()=>r.service.previewMarkdownPlan({project_id:'p',markdown:'# Different plan',source_file_path:plan}),/does not match/);const session=r.service.previewMarkdownPlan({project_id:'p',markdown:fs.readFileSync(plan,'utf8'),source_file_path:plan});assert.equal(r.store.getProject('p').metadata.workspace_root,r.dir);assert.equal(r.service.resolveWorkspaceProject({working_directory:plan,project_id:'p'}).workspace_root,r.dir);assert.equal(session.analysis.source.input_source,plan);r.service.setNodeImplementationPlan({project_id:'p',node_id:r.f.id,markdown:'# Build'});r.service.createProject({project_id:'q',title:'Keep'});assert.throws(()=>r.service.deleteProject({project_id:'p',confirm_title:'Wrong'}),/Confirm deletion/);r.service.deleteProject({project_id:'p',confirm_title:'Project'});assert.equal(r.store.getProject('p'),null);assert.ok(r.store.getProject('q'));for(const table of ['nodes','node_documents','import_sessions','workspace_records','node_revisions','record_revisions','events'])assert.equal(r.store.db.prepare(`SELECT count(*) AS n FROM ${table} WHERE project_id='p'`).get().n,0,table);}finally{r.close();}});

test('dense automatic placement and restored positions have no overlaps',()=>{const boxes=Array.from({length:100},(_,i)=>({id:String(i),x:0,y:0,width:240,height:96+i%6*30}));const placed=placeCards(boxes,{0:{x:20,y:20},1:{x:20,y:20}});for(let i=0;i<placed.length;i++)for(let j=i+1;j<placed.length;j++)assert.equal(intersects(placed[i],placed[j],0),false);const points=routeConnection(placed[0],placed[1],placed);assert.ok(points.length>1);});

test('priority bands form stable, staggered non-circular rings without card overlap',()=>{const boxes=Array.from({length:60},(_,i)=>({id:`feature-${i}`,number:`F${i+1}`,x:0,y:0,width:240,height:100+i%3*25,tier:Math.floor(i/20),detail:false}));const first=placeRadialCards(boxes),again=placeRadialCards(boxes);assert.deepEqual(first,again);assert.ok(first.rings.filter(r=>r.tier===0).length>1);for(let i=0;i<first.boxes.length;i++)for(let j=i+1;j<first.boxes.length;j++)assert.equal(intersects(first.boxes[i],first.boxes[j],0),false);const p0=first.boxes.filter(b=>b.tier===0).map(b=>Math.hypot(b.x+b.width/2,b.y+b.height/2)),p2=first.boxes.filter(b=>b.tier===2).map(b=>Math.hypot(b.x+b.width/2,b.y+b.height/2));assert.ok(Math.max(...p0)<Math.min(...p2));assert.notEqual(ringRadius(900,0,0),ringRadius(900,1,0));});
