import { workspaceTools } from './workspace-tools.mjs';
const obj=(properties={},required=[])=>({type:'object',properties,required,additionalProperties:false});
const s={type:'string'}, b={type:'boolean'}, i={type:'integer'}, n={type:'number'};

export function buildRegistry(service){
  const defs=[];
  const add=(name,description,inputSchema,handler)=>defs.push({name,description,inputSchema,handler});

  add('solution.create_project','Create a Living Solution Graph project.',obj({project_id:s,title:s,description:s,metadata:{type:'object'}},['project_id','title']),a=>service.createProject(a));
  add('solution.delete_project','Permanently delete a project and its graph, plans, memory, and history. Requires its exact title for confirmation.',obj({project_id:s,confirm_title:s},['project_id','confirm_title']),a=>service.deleteProject(a));
  add('solution.resolve_workspace_project','Resolve the current working directory or repository root to its isolated LSG project, adopting an existing repository_root binding or creating one when needed.',obj({working_directory:s,project_id:s,project_title:s,description:s},['working_directory']),a=>service.resolveWorkspaceProject(a));
  add('solution.run_program','Run a compact, bounded LSG query program. Prefer this for routine Codex navigation so large graphs are not dumped into model context.',obj({project_id:s,program:{type:'string',enum:['overview','feature','next_work','missing_plans','search']},reference:s,query:s,cursor:s,limit:{type:'integer',minimum:1,maximum:10}},['project_id','program']),a=>service.runCompactProgram(a));
  add('solution.bootstrap_from_markdown_plan','Import a normal Markdown plan, detect project archetypes, seed domain-aware baseline features/edge cases, expand generic edge cases, and optionally commit the graph baseline. source_file_path binds the project to the plan folder.',obj({project_id:s,project_title:s,file_name:s,markdown:s,file_uri:s,source_file_path:s,mode:{type:'string',enum:['preview_only','create_project_baseline','merge_update']},expected_graph_version:i,policy:{type:'object'},starter_pack_mode:{type:'string'},starter_pack_ids:{type:'array',items:s},min_archetype_confidence:n,allow_model_edge_case_expansion:b,max_edge_cases_per_feature_per_pass:i},['project_id','mode','expected_graph_version']),a=>service.bootstrapFromMarkdownPlan(a));
  add('solution.preview_markdown_plan','Analyze and stage a Markdown plan without mutating graph nodes. Pass source_file_path to bind the project to its folder.',obj({project_id:s,file_name:s,markdown:s,file_uri:s,source_file_path:s,expected_graph_version:i,starter_pack_mode:s,starter_pack_ids:{type:'array',items:s},min_archetype_confidence:n,allow_model_edge_case_expansion:b,max_edge_cases_per_feature_per_pass:i},['project_id','expected_graph_version']),a=>service.previewMarkdownPlan(a));
  add('solution.commit_plan_import','Atomically materialize a previewed Markdown import against an expected graph version.',obj({project_id:s,import_session_id:s,expected_graph_version:i,reason:s},['project_id','import_session_id','expected_graph_version']),a=>service.commitPlanImport(a));
  add('solution.get_plan_import','Read plan import analysis/result metadata.',obj({project_id:s,import_session_id:s},['project_id','import_session_id']),a=>service.getPlanImport(a));
  add('solution.get_bootstrap_report','Return the import analysis, starter evaluations, and current implementation audit.',obj({project_id:s,import_session_id:s},['project_id','import_session_id']),a=>service.getBootstrapReport(a));
  add('solution.reconcile_plan_import','Compare plan implementation claims with current graph implementation truth.',obj({project_id:s,import_session_id:s},['project_id','import_session_id']),a=>service.reconcilePlanImport(a));
  add('solution.set_implementation_state','Set the explicit implemented boolean for a feature/edge case/requirement. Also updates implementation_state, timestamps, optional commit SHA, and stales verification when reopened.',obj({project_id:s,node_id:s,implemented:b,implementation_state:s,expected_graph_version:i,expected_node_version:i,commit_sha:s,reason:s,actor:s},['project_id','node_id','implemented','expected_graph_version']),a=>service.setImplementationState(a));
  add('solution.set_verification_state','Set verification state independently from implementation state and optionally attach evidence.',obj({project_id:s,node_id:s,verification_state:{type:'string',enum:['unverified','verifying','verified','failed','stale']},expected_graph_version:i,expected_node_version:i,evidence:{type:'object'},reason:s,actor:s},['project_id','node_id','verification_state','expected_graph_version']),a=>service.setVerificationState(a));
  add('solution.record_evidence','Attach implementation/test/e2e evidence to a graph node.',obj({project_id:s,node_id:s,kind:s,summary:s,commit_sha:s,artifact_uri:s,details:{type:'object'},expected_graph_version:i,expected_node_version:i,actor:s},['project_id','node_id','summary','expected_graph_version','expected_node_version']),a=>service.recordEvidence(a));
  add('solution.audit_implementation_status','Traverse the entire graph and return implemented, not implemented, verified, unverified, stale, blocked, and plan-claimed status inventories.',obj({project_id:s,types:{type:'array',items:s}},['project_id']),a=>service.auditImplementationStatus(a));
  add('solution.add_edge_case','Let the model insert a newly discovered edge case into the graph under a feature. When the parent is semantic, the edge case keeps semantic numbering and count visibility. New edge cases start implemented=false and unverified.',obj({project_id:s,parent_feature_id:s,title:s,description:s,category:s,severity:s,disposition:s,reason:s,trigger:s,expected_behavior:s,validation_scenario:s,origin:s,actor:s,expected_graph_version:i},['project_id','parent_feature_id','title','expected_graph_version']),a=>service.addEdgeCase(a));
  add('solution.get_graph_view','Return connected graph nodes/edges for rendering. Nodes include live implementation, verification, timestamps, and inherited commit metadata.',obj({project_id:s,include_types:{type:'array',items:s}},['project_id']),a=>service.getGraphView(a));
  add('solution.validate_project_integrity','Run a read-only graph consistency audit for identity collisions, orphan records, unsafe mappings, dependency cycles, incomplete edge-case definitions, and stale semantic runs.',obj({project_id:s,include_details:b,limit:{type:'integer',minimum:1,maximum:500}},['project_id']),a=>service.validateProjectIntegrity(a));
  add('solution.select_node_neighborhood','Select one feature or edge case by node ID, F/E-number, semantic key, or exact title and return it with every directly connected neighbor.',obj({project_id:s,node_id:s,reference:s,max_nodes:{type:'integer',minimum:2,maximum:250}},['project_id']),a=>service.selectNodeNeighborhood(a));
  add('solution.select_node_cascade','Select one feature or edge case and return its direct neighbors plus a chosen number of additional neighbor generations. cascade_depth=1 includes neighbors of neighbors.',obj({project_id:s,node_id:s,reference:s,cascade_depth:{type:'integer',minimum:0,maximum:5},max_nodes:{type:'integer',minimum:2,maximum:250}},['project_id','cascade_depth']),a=>service.selectNodeCascade(a));
  add('solution.search','Search graph nodes by normalized lexical relevance.',obj({project_id:s,query:s,limit:i},['project_id','query']),a=>service.search(a));
  add('solution.find_gaps','Return the current implementation/completeness gaps.',obj({project_id:s},['project_id']),a=>service.findGaps(a));
  add('solution.get_frontier','Return a bounded completion frontier for an implementation agent.',obj({project_id:s,limit:i},['project_id']),a=>service.getFrontier(a));
  add('solution.get_context','Compile project graph + completion frontier + compressed user memory for a model call.',obj({project_id:s,user_id:s,memory_budget_tokens:i,frontier_limit:i,max_nodes:i,max_edges:i},['project_id']),a=>service.getContext(a));
  add('solution.list_starter_packs','List versioned domain starter coverage packs.',obj(),()=>service.listStarterPacks());
  add('solution.detect_project_archetypes','Detect likely project archetypes from Markdown/text.',obj({markdown:s,min_archetype_confidence:n},['markdown']),a=>service.detectProjectArchetypes(a));
  add('solution.apply_starter_pack','Apply one domain starter pack to an existing project graph.',obj({project_id:s,pack_id:s,expected_graph_version:i},['project_id','pack_id','expected_graph_version']),a=>service.applyStarterPack(a));
  add('solution.get_starter_pack_evaluation','Read starter-pack evaluation provenance for a project/import.',obj({project_id:s,import_session_id:s},['project_id']),a=>service.getStarterPackEvaluation(a));
  add('solution.prepare_semantic_feature_set','Create a bounded source-evidence brief for Codex to author a semantic implementation-unit and edge-case proposal. This tool does not modify the live graph.',obj({project_id:s,source_import_id:s,scope:s,max_features:i,source_node_limit:i,actor:s},['project_id']),a=>service.prepareSemanticFeatureSet(a));
  add('solution.stage_semantic_feature_set','Validate, persist, and automatically commit a Codex-authored semantic feature/edge-case proposal. Set auto_commit=false only for an explicitly requested review-only workflow.',obj({project_id:s,run_id:s,proposal:{type:'object'},max_features:i,auto_commit:b,actor:s},['project_id','run_id','proposal']),a=>service.stageSemanticFeatureSet(a));
  add('solution.commit_semantic_feature_set','Atomically materialize an explicitly approved staged semantic proposal into the live graph.',obj({project_id:s,run_id:s,expected_graph_version:i,actor:s},['project_id','run_id','expected_graph_version']),a=>service.commitSemanticFeatureSet(a));
  add('solution.get_semantic_feature_list','Return active Codex-authored implementation units ordered by priority with dependencies, edge cases, and acceptance tests.',obj({project_id:s},['project_id']),a=>service.getSemanticFeatureList(a));
  add('solution.get_semantic_edge_cases','Return semantic edge cases globally or for one semantic feature ID/key.',obj({project_id:s,feature_id:s,semantic_key:s},['project_id']),a=>service.getSemanticEdgeCases(a));
  add('solution.update_semantic_edge_case','Edit a semantic edge case while preserving its stable E-number, semantic key, and source links.',obj({project_id:s,node_id:s,expected_graph_version:i,expected_node_version:i,title:s,description:s,trigger:s,expected_behavior:s,validation_scenario:s,severity:s,actor:s},['project_id','node_id','expected_graph_version','expected_node_version']),a=>service.updateSemanticEdgeCase(a));
  add('solution.delete_semantic_edge_case','Remove an edge case from the active semantic backlog while retaining its history and E-number. Requires exact display ID confirmation.',obj({project_id:s,node_id:s,expected_graph_version:i,expected_node_version:i,confirm_display_id:s,actor:s},['project_id','node_id','expected_graph_version','expected_node_version','confirm_display_id']),a=>service.deleteSemanticEdgeCase(a));
  add('solution.get_semantic_diff','Return a staged or committed semantic proposal diff.',obj({project_id:s,run_id:s},['project_id','run_id']),a=>service.getSemanticDiff(a));
  add('solution.resolve_semantic_feature_reference','Resolve a human reference such as F1, F1.2, or 1 to its semantic feature, descendants, and edge cases before staging an update.',obj({project_id:s,reference:s},['project_id','reference']),a=>service.resolveSemanticFeatureReference(a));
  add('solution.reindex_semantic_features','Assign missing stable F-number display IDs to active semantic features without changing their source evidence.',obj({project_id:s,actor:s},['project_id']),a=>service.reindexSemanticFeatures(a));
  add('solution.update_semantic_feature','Edit a semantic feature while preserving its stable semantic key and F-number. Acceptance tests are synchronized atomically.',obj({project_id:s,node_id:s,expected_graph_version:i,expected_node_version:i,title:s,outcome:s,priority:s,acceptance_criteria:{type:'array',items:s},non_goals:{type:'array',items:s},actor:s},['project_id','node_id','expected_graph_version','expected_node_version']),a=>service.updateSemanticFeature(a));
  add('solution.set_node_implementation_plan','Attach or replace a Markdown implementation plan on a feature or edge case.',obj({project_id:s,node_id:s,file_name:s,markdown:s,expected_document_version:i,actor:s},['project_id','node_id','markdown']),a=>service.setNodeImplementationPlan(a));
  add('solution.get_node_implementation_plan','Read the Markdown implementation plan attached to a feature or edge case.',obj({project_id:s,node_id:s},['project_id','node_id']),a=>service.getNodeImplementationPlan(a));
  add('solution.append_node_implementation_plan','Append a Markdown section to a feature or edge-case plan, preserving existing text and document history.',obj({project_id:s,node_id:s,markdown:s,file_name:s,expected_document_version:i,actor:s},['project_id','node_id','markdown']),a=>service.appendNodeImplementationPlan(a));
  add('solution.delete_node_implementation_plan','Delete an attached Markdown plan after exact file-name confirmation. Definition history remains available.',obj({project_id:s,node_id:s,confirm_file_name:s,expected_document_version:i,actor:s},['project_id','node_id','confirm_file_name']),a=>service.deleteNodeImplementationPlan(a));
  add('solution.get_implementation_plan_coverage','Audit active feature and edge-case nodes with and without written Markdown plans; includes default numbered filenames.',obj({project_id:s,missing_only:b,include_source:b},['project_id']),a=>service.getImplementationPlanCoverage(a));
  add('solution.get_next_missing_plans','Return one bounded page of unwritten implementation plans with source-linked node context and an opaque cursor.',obj({project_id:s,limit:i,cursor:s,include_source:b},['project_id']),a=>service.getNextMissingPlans(a));
  add('solution.stage_plan_batch','Validate and stage 1–25 Markdown plans for human review without changing attached node documents.',obj({project_id:s,expected_graph_version:i,plans:{type:'array',items:{type:'object'}},actor:s},['project_id','expected_graph_version','plans']),a=>service.stagePlanBatch(a));
  add('solution.get_plan_batch','Retrieve a staged or applied Markdown plan batch, including its complete review diff.',obj({project_id:s,batch_id:s},['project_id','batch_id']),a=>service.getPlanBatch(a));
  add('solution.apply_plan_batch','Atomically apply a reviewed plan batch after confirming its exact plan count; reject stale graph or document versions.',obj({project_id:s,batch_id:s,expected_graph_version:i,confirm_plan_count:i,actor:s},['project_id','batch_id','expected_graph_version','confirm_plan_count']),a=>service.applyPlanBatch(a));
  add('solution.export_project_snapshot','Write a compressed, project-scoped JSON snapshot into the managed LSG exports directory without changing the graph.',obj({project_id:s},['project_id']),a=>service.exportProjectSnapshot(a));
  add('solution.restore_project_snapshot','Restore a managed snapshot only when its checksum and exact project title match, and never overwrite an existing project.',obj({file_path:s,expected_sha256:s,confirm_title:s},['file_path','expected_sha256','confirm_title']),a=>service.restoreProjectSnapshot(a));

  add('memory.remember','Store durable user history as a versionable memory atom.',obj({user_id:s,text:s,kind:s,subject:s,value:s,scope:s,project_id:s,confidence:n,salience:n,source:s,metadata:{type:'object'}},['user_id']),a=>service.remember(a));
  add('memory.search','Search active user memory atoms.',obj({user_id:s,project_id:s,query:s,include_inactive:b,limit:i},['user_id']),a=>service.memorySearch(a));
  add('memory.get_context','Return a token-budgeted compressed user-memory projection for the current request/project.',obj({user_id:s,project_id:s,budget_tokens:i},['user_id']),a=>service.memoryContext(a));
  add('memory.correct','Supersede a memory atom with a corrected version rather than destructively overwriting history.',obj({user_id:s,memory_id:s,value:s,kind:s,subject:s,scope:s,project_id:s,confidence:n,salience:n,source:s},['user_id','memory_id','value']),a=>service.memoryCorrect(a));
  add('memory.forget','Mark a memory atom forgotten so it is excluded from future context.',obj({user_id:s,memory_id:s},['user_id','memory_id']),a=>service.memoryForget(a));

  const registry=[...defs,...workspaceTools(service)];
  const category=name=>name.startsWith('memory.')?'memory':name.includes('semantic')||name==='solution.add_edge_case'?'semantic':name.includes('implementation_plan')||name.includes('plan_batch')||name.includes('missing_plans')?'plans':name.includes('activity')||name.includes('node_file')||name.includes('git_history')||name.includes('node_history')?'activity_and_history':name.includes('work')?'work':name.includes('importance')?'importance':name.includes('markdown_plan')||name.includes('plan_import')||name.includes('starter_pack')||name.includes('project_snapshot')||name==='solution.create_project'||name==='solution.delete_project'||name==='solution.resolve_workspace_project'?'projects_and_imports':'graph_and_progress';
  registry.push({name:'solution.get_tool_catalog',description:'Return a compact, searchable and paginated catalog of LSG tools without loading every JSON schema into model context.',inputSchema:obj({query:s,category:s,cursor:{type:'integer',minimum:0},limit:{type:'integer',minimum:1,maximum:25}}),handler:a=>{const query=String(a.query||'').trim().toLowerCase(),wanted=String(a.category||'').trim().toLowerCase(),matches=registry.map(tool=>({name:tool.name,description:tool.description,category:category(tool.name),required:tool.inputSchema.required||[]})).filter(tool=>(!wanted||tool.category===wanted)&&(!query||`${tool.name} ${tool.description}`.toLowerCase().includes(query))).sort((x,y)=>x.name.localeCompare(y.name));const offset=Math.max(0,Number(a.cursor)||0),limit=Math.max(1,Math.min(25,Number(a.limit)||10)),items=matches.slice(offset,offset+limit),next=offset+items.length;return {total:matches.length,cursor:offset,limit,items,next_cursor:next<matches.length?next:null,categories:[...new Set(registry.map(tool=>category(tool.name)))].sort()};}});
  return registry;
}

export function publicTools(registry){return registry.map(({handler,...d})=>d).sort((a,b)=>a.name.localeCompare(b.name));}

export function validateArgs(schema,args){
  args=args??{};
  if(schema.type==='object' && (typeof args!=='object'||Array.isArray(args))) return 'arguments must be an object';
  for(const key of schema.required||[]) if(args[key]===undefined||args[key]===null) return `missing required argument: ${key}`;
  if(schema.additionalProperties===false)for(const key of Object.keys(args))if(!Object.hasOwn(schema.properties||{},key))return `unknown argument: ${key}`;
  const visit=(rule,value,label)=>{
    if(rule.enum&&!rule.enum.includes(value))return `${label} must be one of: ${rule.enum.join(', ')}`;
    if(rule.type==='string'){
      if(typeof value!=='string')return `${label} must be a string`;
      if(rule.minLength!=null&&value.length<rule.minLength)return `${label} must contain at least ${rule.minLength} characters`;
      if(rule.maxLength!=null&&value.length>rule.maxLength)return `${label} must contain at most ${rule.maxLength} characters`;
      if(rule.pattern&&!new RegExp(rule.pattern).test(value))return `${label} has an invalid format`;
    }else if(rule.type==='boolean'){if(typeof value!=='boolean')return `${label} must be a boolean`;
    }else if(rule.type==='integer'){if(!Number.isInteger(value))return `${label} must be an integer`;
    }else if(rule.type==='number'){if(typeof value!=='number'||!Number.isFinite(value))return `${label} must be a finite number`;
    }else if(rule.type==='array'){
      if(!Array.isArray(value))return `${label} must be an array`;
      if(rule.minItems!=null&&value.length<rule.minItems)return `${label} must contain at least ${rule.minItems} items`;
      if(rule.maxItems!=null&&value.length>rule.maxItems)return `${label} must contain at most ${rule.maxItems} items`;
      if(rule.items)for(let index=0;index<value.length;index++){const error=visit(rule.items,value[index],`${label}[${index}]`);if(error)return error;}
    }else if(rule.type==='object'){
      if(value==null||typeof value!=='object'||Array.isArray(value))return `${label} must be an object`;
      for(const required of rule.required||[])if(value[required]===undefined||value[required]===null)return `missing required argument: ${label}.${required}`;
      if(rule.additionalProperties===false)for(const key of Object.keys(value))if(!Object.hasOwn(rule.properties||{},key))return `unknown argument: ${label}.${key}`;
      for(const [key,nested] of Object.entries(value)){const child=rule.properties?.[key];if(child){const error=visit(child,nested,`${label}.${key}`);if(error)return error;}}
    }
    if((rule.type==='integer'||rule.type==='number')&&rule.minimum!=null&&value<rule.minimum)return `${label} must be at least ${rule.minimum}`;
    if((rule.type==='integer'||rule.type==='number')&&rule.maximum!=null&&value>rule.maximum)return `${label} must be at most ${rule.maximum}`;
    return null;
  };
  for(const [key,value] of Object.entries(args)){const rule=schema.properties?.[key];if(rule){const error=visit(rule,value,key);if(error)return error;}}
  return null;
}
